package com.ecoguard.ecoguard.entity;

/**
 * Enumeration of alert types generated by the system.
 * <p>
 * Alerts are triggered when environmental conditions exceed configured thresholds
 * or when an intruder is detected via light spike analysis.
 *
 * @author EcoGuard 
 * @since 1.0
 */
public enum AlertType {
    /**
     * Alert triggered when a sensor reading exceeds configured threshold bounds.
     */
    THRESHOLD,
    
    /**
     * Alert triggered when a sudden light spike indicates possible intruder detection.
     */
    INTRUDER
}

