package com.ecoguard.ecoguard.entity;

import jakarta.persistence.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import lombok.Data;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Represents an alert generated by the system.
 * <p>
 * Alerts are created when sensor readings breach configured thresholds or when
 * an intruder is detected (light spike). Each alert contains the alert type,
 * metric information, value that triggered it, and timestamp.
 *
 * @author EcoGuard 
 * @since 1.0
 */
@Entity
@Table(name = "ALERTS")
@Data
public class Alert {
    /**
     * Default constructor.
     */
    public Alert() {
    }

    /**
     * Unique identifier for the alert.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "alert_id")
    private Long id;

    /**
     * Type of alert that was triggered.
     * Can be THRESHOLD (metric breach) or INTRUDER (light spike detection).
     */
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.VARCHAR)
    @Column(name = "alert_type", nullable = false, length = 20)
    private AlertType alertType;

    /**
     * The metric type associated with this alert.
     * Can be TEMP, HUMIDITY, CO2, or LIGHT.
     */
    @Column(name = "metric_type", length = 20)
    private String metricType;

    /**
     * The sensor value that triggered this alert.
     * Stored with 2 decimal places precision.
     */
    @Column(name = "\"value\"", precision = 10, scale = 2)
    private BigDecimal value;

    /**
     * Timestamp when the alert was generated.
     * Automatically set to current time on persistence.
     */
    @Column(name = "timestamp", nullable = false)
    private LocalDateTime timestamp;

    /**
     * JPA lifecycle callback to set timestamp before persisting.
     * Automatically sets {@code timestamp} to current time if not already set.
     */
    @PrePersist
    public void prePersist() {
        if (timestamp == null) {
            timestamp = LocalDateTime.now();
        }
    }
}